services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: laravel-weather-api
    container_name: laravel-weather-api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:SomeRandomString
      - OPENWEATHER_API_KEY=your_openweather_api_key_here
    expose:
      - 9000

  webserver:
    image: nginx:alpine
    container_name: nginx-webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
