name: atmos_weather_app

services:
  # Laravel API service
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    image: atmos-laravel-api
    container_name: atmos-laravel-api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ../api:/var/www
    networks:
      - atmos-network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    expose:
      - 9000

  # Nginx for Laravel API
  webserver:
    image: nginx:alpine
    container_name: atmos-nginx-webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ../api:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - atmos-network

  # Next.js webapp
  webapp:
    build:
      context: ..
      dockerfile: docker/Dockerfile.webapp
    image: atmos-nextjs-webapp
    container_name: atmos-nextjs-webapp
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ../webapp:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    networks:
      - atmos-network
    depends_on:
      - webserver

networks:
  atmos-network:
    driver: bridge
